/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runalyze

type Body2 struct {
	// Date/Time
	DateTime string `json:"date_time"`
	// Systolic in mmHg
	Systolic int32 `json:"systolic"`
	// Diastolic in mmHg
	Diastolic int32 `json:"diastolic"`
	// Heart Rate in bpm
	HeartRate int32 `json:"heart_rate,omitempty"`
}
