/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runalyze

type Body7 struct {
	// Only date will be stored
	DateTime string `json:"date_time"`
	// Fatigue between 0 and 10
	Fatigue int32 `json:"fatigue,omitempty"`
	// Stress between 0 and 10
	Stress int32 `json:"stress,omitempty"`
	// Mood between 0 and 10
	Mood int32 `json:"mood,omitempty"`
}
