/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runalyze

type Body1 struct {
	Sleep []Apiv1metricsSleep `json:"sleep,omitempty"`
	BodyComposition []Apiv1metricsBodyComposition `json:"bodyComposition,omitempty"`
	BloodPressure []Apiv1metricsBodyComposition `json:"bloodPressure,omitempty"`
	HeartRateRest []Apiv1metricsBodyComposition `json:"heartRateRest,omitempty"`
	HeartRateMax []Apiv1metricsBodyComposition `json:"heartRateMax,omitempty"`
	Mental []Apiv1metricsBodyComposition `json:"mental,omitempty"`
}
