/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package runalyze
// ApiV1MetricsSleep struct for ApiV1MetricsSleep
type ApiV1MetricsSleep struct {
	// Sleep Start Time
	DateTime string `json:"date_time"`
	// Sleep duration in minutes
	Duration float32 `json:"duration"`
	// REM duration in minutes
	RemDuration float32 `json:"rem_duration,omitempty"`
	// Light Sleep duration in Minutes
	LightSleepDuration float32 `json:"light_sleep_duration,omitempty"`
	// Deep Sleep duration in minutes
	DeepSleepDuration float32 `json:"deep_sleep_duration,omitempty"`
	// Awake time in minutes
	AwakeDuration float32 `json:"awake_duration,omitempty"`
	// Sleep quality between 0 and 10
	Quality float32 `json:"quality,omitempty"`
}
