/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runalyze

type Apiv1metricsSleep struct {
	// Sleep Start Time
	DateTime string `json:"date_time"`
	// Sleep duration in minutes
	Duration float64 `json:"duration"`
	// REM duration in minutes
	RemDuration float64 `json:"rem_duration,omitempty"`
	// Light Sleep duration in Minutes
	LightSleepDuration float64 `json:"light_sleep_duration,omitempty"`
	// Deep Sleep duration in minutes
	DeepSleepDuration float64 `json:"deep_sleep_duration,omitempty"`
	// Awake time in minutes
	AwakeDuration float64 `json:"awake_duration,omitempty"`
	// Sleep quality between 0 and 10
	Quality float64 `json:"quality,omitempty"`
}
