/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runalyze

type Body struct {
	// Activity title
	Title string `json:"title,omitempty"`
	// Activity note
	Note string `json:"note,omitempty"`
	// Activity route
	Route string `json:"route,omitempty"`
	// Activity file (*.fit, *.tcx, *.gpx, *.ttbin)
	File []*os.File `json:"file"`
}
