/*
 * Runalyze Personal API
 *
 * Go client for the [Runalyze Personal API](https://runalyze.com/help/article/personal-api).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package runalyze
// ApiV1MetricsBodyComposition struct for ApiV1MetricsBodyComposition
type ApiV1MetricsBodyComposition struct {
	// Date/Time
	___ string `json:"...,omitempty"`
}
